version: "3"

services:
  # Python API
  python-api:
    image: ayanrocks/makaut_python_api
    deploy:
      replicas: 2
    ports:
      - "4001:5000"
    environment:
      FLASK_APP: index.py
    restart: on-failure

  web1:
    image: ayanrocks/makaut_web_app
    deploy:
      replicas: 3
    ports:
      - "4002:4000"
    links:
      - python-api
      - redis
    restart: on-failure

  
  # Redis Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure