version: "3.6"

services:
  # Python API
  python-api:
    build: ./python_api
    deploy:
      replicas: 2
    ports:
      - "4001:5000"
    environment:
      FLASK_APP: index.py
    restart: on-failure

  web1:
    build: ./web
    deploy:
      replicas: 3
    ports:
      - "4002:4000"
    links:
      - python-api
      - redis
    restart: on-failure

  web2:
    build: ./web
    deploy:
      replicas: 3
    ports:
      - "4000"
    links:
      - python-api
      - redis
    restart: on-failure

  web3:
    build: ./web
    deploy:
      replicas: 3
    ports:
      - "4000"
    links:
      - python-api
      - redis
    restart: on-failure

  # Redis Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure

  # NGINX Load Balancer
  nginx:
    build: nginx/
    ports:
      - "4000:4000"
    links:
      - web1
      - web2
      - web3

    volumes:
      - /var/run/docekr.sock:/var/run/docker.sock
