version: "3.6"

networks: 
  microservice: 
    driver: bridge

services:
  # Python API
  python-api:
    build: ./python_api
    deploy:
      replicas: 2
    ports:
      - "4001:5000"
    environment:
      FLASK_APP: index.py
    networks: 
      - microservice

  
  web1:
    build: ./web
    deploy:
      replicas: 3
    ports: 
      - "4000:4000"
    links:
      - python-api
      - redis
    volumes:
      - ./web:/app
    networks: 
      - microservice

  # Redis Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - microservice

      
 