apiVersion: v1
kind: Service              
metadata:
  name: makaut-python-api-svc
spec:  
  ports:
  - port: 80              
    protocol: TCP         
    targetPort: 5000        
  selector:               
    app: makaut-python-api      