apiVersion: v1
kind: Service              
metadata:
  name: makaut-loadbalancer
spec:
  type: LoadBalancer     
  ports:
  - port: 80              
    protocol: TCP         
    targetPort: 4000        
  selector:               
    app: makaut-web      