apiVersion: v1
kind: Service              
metadata:
  name: makaut-redis-service
spec:    
  ports:
  - port: 6379             
    protocol: TCP         
    targetPort: 6379        
  selector:               
    app: makaut-redis      